version: "3.8"
services:
  backend:
    image: masumadu/fastapi-ussd-backend:latest
    container_name: "ussd-be-application"
    env_file:
      - .env
    command: ./start_application.sh
    ports:
      - "8000:8000"
    networks:
      - ussd_service
    depends_on:
      backend_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend_db:
    image: postgres:12
    container_name: "postgres-db"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/service-database:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - ussd_service
    healthcheck:
        test: ["CMD", "pg_isready",  "-U", "${DB_USER}", "-d", "${DB_NAME}"]

  redis:
    image: redis:6.2.6-alpine
    container_name: "redis-server"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "3000:6379"
    networks:
      - ussd_service
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  ussd_service:
    name: ussd_network
