"""user_model_rename_column

Revision ID: 3fb986d387e7
Revises: abe89433f295
Create Date: 2024-05-14 08:47:42.393467

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fb986d387e7"
down_revision = "abe89433f295"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(), nullable=True))
    op.drop_column("users", "gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("gender", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "address")
    # ### end Alembic commands ###
